kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 10000
        hostPort: 10000
        protocol: TCP
      - containerPort: 10002
        hostPort: 10002
        protocol: TCP
      - containerPort: 10004
        hostPort: 10004
        protocol: TCP
